#!/usr/bin/env python3
"""Install the repository's DSH Client and Codex Host overlays into one harness.

The installer is intentionally conservative.  It validates both complete
source trees and every DSH registration anchor before writing anything.
After the first successful install, ``.dsh-managed/manifest.json`` records a
hash for every managed file and for each registration file.  A later source
revision may replace files only when the target still matches that manifest;
an edit made in the harness therefore fails closed instead of being silently
overwritten.  The manifest itself lives below a generated directory and is
not part of either source tree.

There is no recursive delete operation.  Obsolete files from a previous
managed manifest are removed one at a time only after their recorded hash is
verified.  Build output and package-manager directories remain untouched.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import stat
import sys
import tempfile
from pathlib import Path
from typing import Iterable, NoReturn


PLUGIN_PACKAGE = "@deepseek-ai/dsh-client-ui-voice"
PLUGIN_TARGET = Path("packages/client/ui-voice")
HOST_PACKAGE = "@deepseek-ai/dsh-host-codex"
HOST_TARGET = Path("packages/host/codex")
PLUGIN_DEPENDENCY_ANCHOR = "@deepseek-ai/dsh-client-ui-trajectory"
HOST_DEPENDENCY_ANCHOR = "@deepseek-ai/dsh-host-plugin-inventory"
GENERATED_TOP_LEVEL = {"lib", "node_modules", ".turbo", ".cache"}
MANAGED_DIR = Path(".dsh-managed")
MANIFEST_RELATIVE = MANAGED_DIR / "manifest.json"
MANIFEST_SCHEMA = 1
REGISTRATION_RELATIVES = (
    Path("tsconfig.client.json"),
    Path("tsconfig.host.json"),
    Path("packages/api/remotes/src/client/index.ts"),
    Path("packages/api/remotes/package.json"),
    Path("packages/api/remotes/tsconfig.client.json"),
    Path("packages/bundle/web-app/cordis.patch.yml"),
    Path("packages/bundle/web-app/package.json"),
    Path("packages/host/apiproxy/src/api-proxy.ts"),
    Path("packages/client/runtime/src/client/sessions/manager.ts"),
)
# Manifests written before Codex-only turns participated in the core Session
# list metadata projection. Accepted only so one installer run can migrate
# them to the current nine-anchor shape.
LEGACY_CODEX_REGISTRATION_RELATIVES = REGISTRATION_RELATIVES[:-1]
LEGACY_HOST_CODEX_REGISTRATION_RELATIVES = REGISTRATION_RELATIVES[:-2]
# Transitional manifests written by the previous ui-voice dual-aggregate
# overlay.  They are accepted only to migrate in one installer invocation.
LEGACY_SPLIT_REGISTRATION_RELATIVES = (
    Path("tsconfig.client.json"),
    Path("tsconfig.host.json"),
    Path("packages/bundle/web-app/cordis.patch.yml"),
    Path("packages/bundle/web-app/package.json"),
)
LEGACY_REGISTRATION_RELATIVES = (
    Path("tsconfig.client.json"),
    Path("packages/bundle/web-app/cordis.patch.yml"),
    Path("packages/bundle/web-app/package.json"),
)
# Generated by the pinned harness after the overlay is installed.  Their
# hashes are kept separately from the plugin tree so bootstrap can recognize
# its own expected dirty files on a later run.
PERSISTENCE_CATALOG_RELATIVES = (
    Path("docs/persistence-catalog.md"),
    Path("packages/core/session/src/known-event-types.ts"),
)
HEX64_RE = re.compile(r"^[0-9a-f]{64}$")


class InstallerError(RuntimeError):
    """An expected safety or structure check failed."""


def fail(message: str) -> NoReturn:
    raise InstallerError(message)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Install dsh-plugin into a pinned DeepSeek Harness checkout."
    )
    parser.add_argument(
        "--harness",
        type=Path,
        default=None,
        help="exact harness checkout to update (defaults to DSH_HARNESS)",
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "dsh-plugin",
        help="plugin source directory (defaults to this repository's dsh-plugin)",
    )
    parser.add_argument(
        "--host-source",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "dsh-host-codex",
        help="Codex Host package source (defaults to this repository's dsh-host-codex)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="validate all anchors and print changes without writing files",
    )
    parser.add_argument(
        "--record-lock",
        action="store_true",
        help="record the current harness pnpm lockfile in the managed manifest",
    )
    parser.add_argument(
        "--pnpm-version",
        default=None,
        help="pnpm version to record alongside --record-lock",
    )
    parser.add_argument(
        "--record-catalog",
        action="store_true",
        help="record the pinned harness persistence-catalog output hashes",
    )
    return parser.parse_args(argv)


def ensure_no_symlink(path: Path, label: str) -> None:
    if path.is_symlink():
        fail(f"{label} must not be a symlink: {path}")


def source_files(source: Path) -> list[Path]:
    files: list[Path] = []
    for path in sorted(source.rglob("*")):
        if path.is_symlink():
            fail(f"plugin source contains a symlink: {path}")
        relative = path.relative_to(source)
        # Generated trees are never source provenance. Check symlinks before
        # pruning so a top-level generated symlink cannot bypass the source
        # safety gate. Legacy generated entries remain untouched in targets.
        if _is_generated(relative):
            continue
        if path.is_file():
            files.append(relative)
    if not files:
        fail(f"plugin source is empty: {source}")
    return files


def target_files(target: Path) -> tuple[set[Path], set[Path]]:
    """Return regular files and symlink paths below target."""

    files: set[Path] = set()
    symlinks: set[Path] = set()
    for path in sorted(target.rglob("*")):
        relative = path.relative_to(target)
        if path.is_symlink():
            symlinks.add(relative)
        elif path.is_file():
            files.add(relative)
    return files, symlinks


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    ensure_no_symlink(path, "managed file")
    try:
        return sha256_bytes(path.read_bytes())
    except OSError as exc:
        fail(f"cannot hash {path}: {exc}")


def persistence_catalog_hashes(harness: Path) -> dict[str, str]:
    """Hash generated persistence artifacts without following symlinks."""

    result: dict[str, str] = {}
    for relative in PERSISTENCE_CATALOG_RELATIVES:
        path = harness / relative
        ensure_no_symlink(path, "persistence catalog artifact")
        if not path.is_file():
            fail(f"persistence catalog artifact is missing: {path}")
        result[relative.as_posix()] = sha256_file(path)
    return result


def tree_digest(file_hashes: dict[str, str]) -> str:
    """Hash sorted relative names and file hashes for a deterministic tree id."""

    digest = hashlib.sha256()
    for relative in sorted(file_hashes):
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(file_hashes[relative].encode("ascii"))
        digest.update(b"\n")
    return digest.hexdigest()


def validate_source(source: Path, expected_package: str, label: str) -> list[Path]:
    package_file = source / "package.json"
    if not package_file.is_file():
        fail(f"{label} source has no package.json: {package_file}")
    try:
        package = json.loads(package_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"cannot parse {label} package.json: {exc}")
    if package.get("name") != expected_package:
        fail(
            f"{label} source package name drifted: "
            f"expected {expected_package!r}, got {package.get('name')!r}"
        )
    return source_files(source)


def validate_hash_map(value: object, label: str) -> dict[str, str]:
    if not isinstance(value, dict):
        fail(f"managed manifest {label} must be an object")
    result: dict[str, str] = {}
    for key, item in value.items():
        key_path = Path(key) if isinstance(key, str) else Path(".")
        if (
            not isinstance(key, str)
            or not key
            or key_path.is_absolute()
            or any(part in {"", ".", ".."} for part in key_path.parts)
            or "\\" in key
        ):
            fail(f"managed manifest {label} contains an invalid path")
        if not isinstance(item, str) or not HEX64_RE.fullmatch(item):
            fail(f"managed manifest {label} contains an invalid SHA-256: {key}")
        result[key] = item
    return result


def load_manifest(target: Path) -> dict[str, object] | None:
    """Load and structurally validate the managed manifest, if present."""

    managed_dir = target / MANAGED_DIR
    manifest_path = target / MANIFEST_RELATIVE
    if managed_dir.is_symlink():
        fail(f"managed directory must not be a symlink: {managed_dir}")
    if manifest_path.is_symlink():
        fail(f"managed manifest must not be a symlink: {manifest_path}")
    if not manifest_path.exists():
        if managed_dir.exists() and not managed_dir.is_dir():
            fail(f"managed path is not a directory: {managed_dir}")
        return None
    if not managed_dir.is_dir():
        fail(f"managed manifest parent is not a directory: {managed_dir}")
    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"cannot parse managed manifest {manifest_path}: {exc}")
    if not isinstance(data, dict):
        fail(f"managed manifest must be an object: {manifest_path}")
    if data.get("schemaVersion") != MANIFEST_SCHEMA:
        fail(f"unsupported managed manifest schemaVersion: {manifest_path}")
    if data.get("installer") != "dsh-plugin":
        fail(f"managed manifest installer identity drifted: {manifest_path}")
    if data.get("target") != PLUGIN_TARGET.as_posix():
        fail(f"managed manifest target drifted: {manifest_path}")
    if data.get("source") != "dsh-plugin":
        fail(f"managed manifest source drifted: {manifest_path}")

    files = validate_hash_map(data.get("files"), "files")
    source_digest = data.get("sourceTreeSha256")
    if not isinstance(source_digest, str) or not HEX64_RE.fullmatch(source_digest):
        fail(f"managed manifest sourceTreeSha256 is invalid: {manifest_path}")
    if tree_digest(files) != source_digest:
        fail(f"managed manifest sourceTreeSha256 does not match files: {manifest_path}")

    host_files_value = data.get("hostFiles")
    host_source_digest = data.get("hostSourceTreeSha256")
    if host_files_value is not None or host_source_digest is not None:
        host_files = validate_hash_map(host_files_value, "hostFiles")
        if not isinstance(host_source_digest, str) or not HEX64_RE.fullmatch(
            host_source_digest
        ):
            fail(f"managed manifest hostSourceTreeSha256 is invalid: {manifest_path}")
        if tree_digest(host_files) != host_source_digest:
            fail(
                "managed manifest hostSourceTreeSha256 does not match hostFiles: "
                f"{manifest_path}"
            )

    registrations = validate_hash_map(data.get("registrations"), "registrations")
    expected_registration_sets = {
        frozenset(path.as_posix() for path in REGISTRATION_RELATIVES),
        frozenset(path.as_posix() for path in LEGACY_CODEX_REGISTRATION_RELATIVES),
        frozenset(path.as_posix() for path in LEGACY_HOST_CODEX_REGISTRATION_RELATIVES),
        frozenset(path.as_posix() for path in LEGACY_SPLIT_REGISTRATION_RELATIVES),
        frozenset(path.as_posix() for path in LEGACY_REGISTRATION_RELATIVES),
    }
    if frozenset(registrations) not in expected_registration_sets:
        fail(f"managed manifest registrations are incomplete: {manifest_path}")

    catalog = data.get("catalog")
    if catalog is not None:
        if not isinstance(catalog, dict):
            fail(f"managed manifest catalog must be an object or omitted: {manifest_path}")
        if catalog.get("generator") != "gen-persistence-catalog":
            fail(f"managed manifest catalog generator drifted: {manifest_path}")
        catalog_files = validate_hash_map(catalog.get("files"), "catalog.files")
        expected_catalog = {path.as_posix() for path in PERSISTENCE_CATALOG_RELATIVES}
        if set(catalog_files) != expected_catalog:
            fail(f"managed manifest catalog files are incomplete: {manifest_path}")

    lock = data.get("lock")
    if lock is not None:
        if not isinstance(lock, dict):
            fail(f"managed manifest lock must be an object or null: {manifest_path}")
        if lock.get("path") != "pnpm-lock.yaml":
            fail(f"managed manifest lock path drifted: {manifest_path}")
        if not isinstance(lock.get("sha256"), str) or not HEX64_RE.fullmatch(lock["sha256"]):
            fail(f"managed manifest lock SHA-256 is invalid: {manifest_path}")
        version = lock.get("pnpmVersion")
        if version is not None and (not isinstance(version, str) or not version):
            fail(f"managed manifest pnpmVersion is invalid: {manifest_path}")
    return data


def validate_manifest_registrations(
    harness: Path, manifest: dict[str, object] | None
) -> None:
    if manifest is None:
        return
    registrations = manifest["registrations"]
    assert isinstance(registrations, dict)
    for relative, expected in registrations.items():
        path = harness / relative
        actual = sha256_file(path)
        if actual != expected:
            fail(
                "managed DSH registration anchor drifted; refusing to overwrite: "
                f"{relative}"
            )


def _is_generated(relative: Path) -> bool:
    return bool(relative.parts) and relative.parts[0] in GENERATED_TOP_LEVEL


def assembled_client_tsconfig(source: Path) -> bytes:
    """Rewrite the standalone client leaf for its installed workspace path.

    The source checkout intentionally extends the pinned harness through
    ``../.runtime/deepseek-harness`` so it can typecheck in this repository.
    Once copied below ``packages/client/ui-voice`` the same references must be
    rooted at the harness checkout itself.  This is a target-only transform;
    the source file is never modified and the transformed bytes are recorded
    in the managed manifest so reruns remain drift-checked.
    """

    try:
        text = source.read_text(encoding="utf-8")
    except OSError as exc:
        fail(f"cannot read standalone client tsconfig {source}: {exc}")
    standalone_prefix = "../.runtime/deepseek-harness/"
    workspace_prefix = "../../../"
    if standalone_prefix not in text:
        fail(
            "standalone client tsconfig must contain the exact pinned harness "
            f"prefix {standalone_prefix!r}: {source}"
        )
    result = text.replace(standalone_prefix, workspace_prefix)
    if standalone_prefix in result or "../.runtime/deepseek-harness" in result:
        fail(f"assembled client tsconfig retained a standalone .runtime path: {source}")
    if '"extends": "../../../tsconfig.base.client.json"' not in result:
        fail(f"assembled client tsconfig has no workspace-relative base config: {source}")
    return result.encode("utf-8")


def assembled_host_tsconfig(source: Path) -> bytes:
    """Rewrite the standalone Codex Host leaf for its installed workspace path.

    The Host source lives beside ``.runtime/deepseek-harness`` in this
    repository, while the installed package lives at
    ``packages/host/codex``.  Package references therefore need one extra
    mapping: a source ``.../packages/core/...`` reference becomes
    ``../../core/...`` from the installed Host package; vendor references
    remain rooted at ``../../../vendor``.
    """

    try:
        text = source.read_text(encoding="utf-8")
    except OSError as exc:
        fail(f"cannot read standalone Host tsconfig {source}: {exc}")
    standalone_prefix = "../.runtime/deepseek-harness/"
    if standalone_prefix not in text:
        fail(
            "standalone Host tsconfig must contain the exact pinned harness "
            f"prefix {standalone_prefix!r}: {source}"
        )
    result = text.replace(
        standalone_prefix + "packages/", "../../"
    ).replace(
        standalone_prefix + "vendor/", "../../../vendor/"
    ).replace(standalone_prefix, "../../../")
    if standalone_prefix in result or "../.runtime/deepseek-harness" in result:
        fail(f"assembled Host tsconfig retained a standalone .runtime path: {source}")
    if '"extends": "../../../tsconfig.base.json"' not in result:
        fail(f"assembled Host tsconfig has no workspace-relative base config: {source}")
    return result.encode("utf-8")


def assembled_host_test_source(source: Path, relative: Path) -> bytes | None:
    """Rewrite standalone Host integration-test runtime imports only."""

    if not relative.as_posix().startswith("tests/") or not relative.name.endswith(".host.spec.ts"):
        return None
    try:
        text = (source / relative).read_text(encoding="utf-8")
    except OSError as exc:
        fail(f"cannot read standalone Host test {source / relative}: {exc}")
    standalone_prefix = "../../.runtime/deepseek-harness/"
    if standalone_prefix not in text:
        return None
    # Installed tests are four directories below the harness root:
    # packages/host/codex/tests -> ../../../../.
    return text.replace(standalone_prefix, "../../../../").encode("utf-8")


def validate_target_generated_files(
    target_file_set: set[Path], symlink_set: set[Path]
) -> None:
    # Generated output is ignored only below an exact top-level directory.
    # The directory itself must not be a symlink: accepting ``lib -> …`` (or
    # ``node_modules -> …``) would make later mkdir/copy operations follow a
    # path outside the managed target.  Package-manager links *inside*
    # node_modules are an expected generated shape, however, and are never
    # traversed or copied by this installer; links in lib/.turbo/.cache are
    # not expected and remain rejected.
    unsafe_symlinks = sorted(
        relative
        for relative in symlink_set
        if (
            not _is_generated(relative)
            or len(relative.parts) == 1
            or relative.parts[0] != "node_modules"
        )
    )
    if unsafe_symlinks:
        fail(
            "plugin target contains symlink(s); refusing to follow or replace: "
            + ", ".join(str(path) for path in unsafe_symlinks)
        )

    for relative in target_file_set:
        if relative.parts and relative.parts[0] == MANAGED_DIR.name:
            if relative != MANIFEST_RELATIVE:
                fail(
                    "managed directory contains an unexpected file; refusing to "
                    f"modify it: {relative}"
                )


def validate_plugin_tree(
    source: Path,
    target: Path,
    files: Iterable[Path],
    manifest: dict[str, object] | None,
    *,
    manifest_key: str = "files",
    label: str = "plugin",
    transformed_files: dict[Path, bytes] | None = None,
) -> tuple[list[Path], list[Path], dict[str, str]]:
    """Preflight one managed source tree without changing the target."""

    expected = set(files)
    transformed_files = transformed_files or {}
    source_hashes = {
        relative.as_posix(): sha256_bytes(transformed_files[relative])
        if relative in transformed_files
        else sha256_file(source / relative)
        for relative in expected
    }
    old_hashes = (
        validate_hash_map(manifest.get(manifest_key), manifest_key)
        if manifest and manifest.get(manifest_key) is not None
        else {}
    )

    if target.exists():
        ensure_no_symlink(target, f"{label} target")
        if not target.is_dir():
            fail(f"{label} target is not a directory: {target}")
        target_file_set, symlink_set = target_files(target)
        validate_target_generated_files(target_file_set, symlink_set)
    else:
        target_file_set = set()

    # Generated output may be present in a legacy manifest or in the target,
    # but it is never provenance for the source overlay.  Keep the complete
    # source hash map for the eventual manifest/copy plan while excluding
    # exact generated top-level paths from adoption/drift comparisons.
    expected_strings = {
        relative
        for relative in source_hashes
        if not _is_generated(Path(relative))
    }
    current_hashes: dict[str, str] = {}
    for relative in sorted(expected & target_file_set):
        if _is_generated(relative):
            continue
        current_hashes[relative.as_posix()] = sha256_file(target / relative)

    if manifest is not None:
        missing_old = sorted(set(current_hashes) - set(old_hashes))
        if missing_old:
            fail(
                f"{label} target contains files outside its managed manifest; "
                "refusing to overwrite: "
                + ", ".join(missing_old)
            )
        changed_old = sorted(
            relative
            for relative, actual in current_hashes.items()
            if old_hashes.get(relative) != actual
        )
        if changed_old:
            fail(
                f"{label} target drifted; refusing to overwrite: "
                + ", ".join(changed_old)
            )
    else:
        # A pre-manifest target has no provenance that can justify replacing
        # an existing file.  An empty target is installable; a non-empty target
        # may only be adopted when its complete source tree already matches
        # this source byte-for-byte.  Generated directories are intentionally
        # excluded from this comparison by _is_generated below.
        non_generated_files = {
            relative.as_posix()
            for relative in target_file_set
            if not _is_generated(relative) and relative != MANIFEST_RELATIVE
        }
        if non_generated_files:
            if non_generated_files != expected_strings:
                missing = sorted(expected_strings - non_generated_files)
                extras = sorted(non_generated_files - expected_strings)
                details = []
                if missing:
                    details.append("missing: " + ", ".join(missing))
                if extras:
                    details.append("extra: " + ", ".join(extras))
                fail(
                    f"manifestless {label} target is not a complete current source "
                    "tree; refusing to adopt: " + "; ".join(details)
                )
            changed = sorted(
                relative
                for relative, actual in current_hashes.items()
                if actual != source_hashes[relative]
            )
            if changed:
                fail(
                    f"manifestless {label} target differs from current source; "
                    "refusing to overwrite: " + ", ".join(changed)
                )

    obsolete: set[Path] = set()
    if manifest is not None:
        for relative in sorted(set(old_hashes) - expected_strings):
            if _is_generated(Path(relative)):
                # Build outputs are never removed by overlay reconciliation,
                # even when an older manifest recorded them as managed.
                continue
            path = target / relative
            if not path.exists():
                continue
            if path.is_symlink():
                fail(f"managed obsolete {label} file is a symlink; refusing to remove: {relative}")
            actual = sha256_file(path)
            if actual != old_hashes[relative]:
                fail(f"managed obsolete file drifted; refusing to remove: {relative}")
            obsolete.add(Path(relative))

    extras = sorted(
        relative
        for relative in target_file_set - expected
        if not _is_generated(relative)
        and relative != MANIFEST_RELATIVE
        and relative not in obsolete
    )
    if extras:
        fail(
            f"{label} target contains unexpected files; refusing to delete them: "
            + ", ".join(str(path) for path in extras)
        )

    missing_or_changed: list[Path] = []
    for relative in sorted(expected):
        destination = target / relative
        if relative not in target_file_set:
            missing_or_changed.append(relative)
        elif sha256_file(destination) != source_hashes[relative.as_posix()]:
            missing_or_changed.append(relative)
    return missing_or_changed, sorted(obsolete), source_hashes


def split_lines(text: str) -> tuple[list[str], str]:
    newline = "\r\n" if "\r\n" in text else "\n"
    return text.splitlines(keepends=True), newline


def line_without_ending(line: str) -> str:
    return line.removesuffix("\n").removesuffix("\r")


def rewrite_tsconfig(path: Path, dry_run: bool) -> tuple[str, bool]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        fail(f"cannot read {path}: {exc}")
    lines, newline = split_lines(text)

    voice_token = "packages/client/ui-voice"
    entry_re = re.compile(
        r'^(?P<indent>[ \t]*)\{[ \t]*"path"[ \t]*:[ \t]*'
        r'"\./packages/client/ui-voice(?:/tsconfig\.client\.json)?"'
        r'[ \t]*\}[,]?[ \t]*(?://.*)?$'
    )
    voice_lines = [index for index, line in enumerate(lines) if voice_token in line]
    valid_entries = [
        index for index, line in enumerate(lines)
        if entry_re.fullmatch(line_without_ending(line))
    ]
    if voice_lines and (len(voice_lines) != 1 or len(valid_entries) != 1):
        fail(f"tsconfig.client.json has a malformed or duplicate ui-voice entry: {path}")

    anchor_re = re.compile(
        r'^(?P<indent>[ \t]*)\{[ \t]*"path"[ \t]*:[ \t]*'
        r'"\./packages/client/ui-trajectory"[ \t]*\},[ \t]*(?://.*)?$'
    )
    anchors = [
        index
        for index, line in enumerate(lines)
        if anchor_re.fullmatch(line_without_ending(line))
    ]
    if len(anchors) != 1:
        fail(
            "tsconfig.client.json must contain exactly one comma-terminated "
            f"ui-trajectory anchor; found {len(anchors)}: {path}"
        )

    if valid_entries:
        index = valid_entries[0]
        line = line_without_ending(lines[index])
        if '"./packages/client/ui-voice"' in line:
            return text, False
        match = entry_re.fullmatch(line)
        assert match is not None
        replacement = (
            match.group("indent")
            + '{ "path": "./packages/client/ui-voice" },'
            + newline
        )
        new_lines = list(lines)
        new_lines[index] = replacement
        return "".join(new_lines), True

    anchor_index = anchors[0]
    anchor_match = anchor_re.fullmatch(line_without_ending(lines[anchor_index]))
    assert anchor_match is not None
    inserted = (
        anchor_match.group("indent")
        + '{ "path": "./packages/client/ui-voice" },'
        + newline
    )
    new_lines = lines[: anchor_index + 1] + [inserted] + lines[anchor_index + 1 :]
    return "".join(new_lines), True


def rewrite_host_tsconfig(path: Path, dry_run: bool) -> tuple[str, bool]:
    """Register the independent Codex Host package in the Host graph."""

    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        fail(f"cannot read {path}: {exc}")
    lines, newline = split_lines(text)

    codex_token = "packages/host/codex"
    codex_re = re.compile(
        r'^(?P<indent>[ \t]*)\{[ \t]*"path"[ \t]*:[ \t]*'
        r'"\./packages/host/codex"[ \t]*\}[,]?[ \t]*(?://.*)?$'
    )
    old_voice_re = re.compile(
        r'^(?P<indent>[ \t]*)\{[ \t]*"path"[ \t]*:[ \t]*'
        r'"\./packages/client/ui-voice(?:/tsconfig\.host\.json)?"'
        r'[ \t]*\}[,]?[ \t]*(?://.*)?$'
    )
    codex_lines = [
        index for index, line in enumerate(lines)
        if codex_token in line
    ]
    valid_codex = [
        index for index, line in enumerate(lines)
        if codex_re.fullmatch(line_without_ending(line))
    ]
    old_voice = [
        index for index, line in enumerate(lines)
        if old_voice_re.fullmatch(line_without_ending(line))
    ]
    if codex_lines and (len(codex_lines) != 1 or len(valid_codex) != 1):
        fail(f"tsconfig.host.json has a malformed or duplicate Codex Host entry: {path}")
    if len(old_voice) > 1:
        fail(f"tsconfig.host.json has duplicate legacy ui-voice Host entries: {path}")

    anchor_re = re.compile(
        r'^(?P<indent>[ \t]*)\{[ \t]*"path"[ \t]*:[ \t]*'
        r'"\./packages/api/remotes/tsconfig\.host\.json"[ \t]*\},[ \t]*'
        r'(?://.*)?$'
    )
    anchors = [
        index for index, line in enumerate(lines)
        if anchor_re.fullmatch(line_without_ending(line))
    ]
    if len(anchors) != 1:
        fail(
            "tsconfig.host.json must contain exactly one comma-terminated "
            f"api/remotes Host anchor; found {len(anchors)}: {path}"
        )

    if valid_codex:
        return text, False

    # Migrate the previous dual-aggregate ui-voice Host registration in place.
    if old_voice:
        legacy_index = old_voice[0]
        legacy_match = old_voice_re.fullmatch(line_without_ending(lines[legacy_index]))
        assert legacy_match is not None
        replacement = (
            legacy_match.group("indent")
            + '{ "path": "./packages/host/codex" },'
            + newline
        )
        new_lines = list(lines)
        new_lines[legacy_index] = replacement
        return "".join(new_lines), True

    anchor_index = anchors[0]
    anchor_match = anchor_re.fullmatch(line_without_ending(lines[anchor_index]))
    assert anchor_match is not None
    inserted = (
        anchor_match.group("indent")
        + '{ "path": "./packages/host/codex" },'
        + newline
    )
    new_lines = lines[: anchor_index + 1] + [inserted] + lines[anchor_index + 1 :]
    return "".join(new_lines), True


def rewrite_api_proxy_codex_session_semantics(
    path: Path, dry_run: bool
) -> tuple[str, bool]:
    """Make a durable Codex user turn visible and non-reusable in Session lists."""

    del dry_run
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        fail(f"cannot read {path}: {exc}")

    old_blank = """function sessionBlank(session: Session): boolean {
  return !session.events.some(event => event.type === 'turn/start')
}"""
    interim_blank = """function sessionBlank(session: Session): boolean {
  return !session.events.some(event =>
    event.type === 'turn/start' || event.type === 'codex/user-start'
  )
}"""
    new_blank = """function sessionBlank(session: Session): boolean {
  return !session.events.some(event =>
    event.type === 'turn/start' || (event.type as string) === 'codex/user-start'
  )
}"""
    old_apply = """  const blank = state.blank && event.type !== 'turn/start'
  const lastPromptAt = event.type === 'user/message' && event.data.source.kind === 'user'
    ? event.time
    : state.lastPromptAt"""
    interim_apply = """  const blank = state.blank
    && event.type !== 'turn/start'
    && event.type !== 'codex/user-start'
  const lastPromptAt = (
    event.type === 'user/message' && event.data.source.kind === 'user'
  ) || event.type === 'codex/user-start'
    ? event.time
    : state.lastPromptAt"""
    new_apply = """  const eventType = event.type as string
  const blank = state.blank
    && eventType !== 'turn/start'
    && eventType !== 'codex/user-start'
  const lastPromptAt = (
    event.type === 'user/message' && event.data.source.kind === 'user'
  ) || eventType === 'codex/user-start'
    ? event.time
    : state.lastPromptAt"""
    old_version = """      apply: applySessionListMetadata,
      view: state => state,
      stateVersion: 1,
    })"""
    new_version = """      apply: applySessionListMetadata,
      view: state => state,
      stateVersion: 2,
    })"""

    pairs = (
        ((old_blank, interim_blank), new_blank, "sessionBlank"),
        ((old_apply, interim_apply), new_apply, "Session-list metadata apply"),
        ((old_version,), new_version, "Session-list metadata stateVersion"),
    )
    changed = False
    for old_variants, new, label in pairs:
        new_count = text.count(new)
        old_counts = tuple(text.count(old) for old in old_variants)
        if new_count == 1 and sum(old_counts) == 0:
            continue
        if sum(old_counts) != 1 or new_count != 0:
            fail(f"api-proxy Codex {label} anchor drifted: {path}")
        old = old_variants[old_counts.index(1)]
        text = text.replace(old, new, 1)
        changed = True
    return text, changed


def rewrite_client_manager_session_metadata(
    path: Path, dry_run: bool
) -> tuple[str, bool]:
    """Mirror the Host Session-list metadata push into the live Client row."""

    del dry_run
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        fail(f"cannot read {path}: {exc}")

    old = """    if (frame.type === 'session/projection') {
      // Finished host-computed value: land it in the resident store whether or
      // not the Session is instantiated (list rows read the 'title' key). The
      // synchronous markDirty keeps the list snapshot same-tick fresh (the
      // store's own any-key channel is microtask-batched).
      this.projectionStore(frame.sessionId).apply(frame.key, frame.value, frame.seq)
      this.notifier.markDirty()
      return
    }"""
    new = """    if (frame.type === 'session/projection') {
      // Session-list metadata is both a projection value and the authority for
      // the live row. Mirror its monotonic non-blank/recency facts immediately
      // so New Session cannot reuse a Codex-only conversation before a pull.
      if (frame.key === 'sessionListMetadata') {
        const metadata = frame.value as { blank: boolean; lastPromptAt: number | null }
        if (!metadata.blank) {
          this.recordMutation({ kind: 'engaged', sessionId: frame.sessionId })
          this.sessions.get(frame.sessionId)?.handleBlank(false)
        }
        if (metadata.lastPromptAt !== null) {
          this.recordMutation({
            kind: 'activity', sessionId: frame.sessionId, updatedAt: metadata.lastPromptAt,
          })
        }
      }
      // Finished host-computed value: land it in the resident store whether or
      // not the Session is instantiated (list rows read the 'title' key). The
      // synchronous markDirty keeps the list snapshot same-tick fresh (the
      // store's own any-key channel is microtask-batched).
      this.projectionStore(frame.sessionId).apply(frame.key, frame.value, frame.seq)
      this.notifier.markDirty()
      return
    }"""
    old_count = text.count(old)
    new_count = text.count(new)
    if new_count == 1 and old_count == 0:
        return text, False
    if old_count != 1 or new_count != 0:
        fail(f"client manager Session-list metadata anchor drifted: {path}")
    return text.replace(old, new, 1), True


def rewrite_api_remotes_client(path: Path, dry_run: bool) -> tuple[str, bool]:
    """Add Codex's Remote and client-safe type vocabulary to api/remotes."""

    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        fail(f"cannot read {path}: {exc}")
    lines, newline = split_lines(text)

    remote_spec = "@deepseek-ai/dsh-host-codex/remote"
    # `types.ts` is Host implementation vocabulary and imports Cordis/Agent.
    # Only the primitive Remote face may enter the Client assembly graph.
    types_spec = "@deepseek-ai/dsh-host-codex/remote-types"
    legacy_types_spec = "@deepseek-ai/dsh-host-codex/types"
    event_types_spec = "@deepseek-ai/dsh-host-codex/event-types"
    package_token = "@deepseek-ai/dsh-host-codex"
    type_export_line = (
        "export type { CodexAccountProof, CodexApprovalDecision, CodexApprovalResult, "
        "CodexCapability, CodexCharacter, CodexExecutionView, CodexInterruptResult, "
        "CodexLoginCancelResult, CodexLoginStartResult, CodexLoginStatusResult, "
        "CodexModelCatalogResult, CodexModelOption, CodexModelSelection, "
        "CodexReasoningEffortOption, CodexRuntimeStatus, CodexSafeErrorCode, "
        "CodexServiceTierOption, CodexStartRequest, CodexStartResult, CodexStatus, "
        "CodexTerminalStatus } from '" + types_spec + "'"
    )
    event_export_line = f"export type {{ CodexSessionEventMap }} from '{event_types_spec}'"

    import_re = re.compile(
        r"^import[ \t]+codexRemote[ \t]+from[ \t]+['\"]"
        + re.escape(remote_spec)
        + r"['\"];?[ \t]*$"
    )
    import_matches = [
        index for index, line in enumerate(lines)
        if import_re.fullmatch(line_without_ending(line))
    ]
    package_mentions = [
        index for index, line in enumerate(lines) if package_token in line
    ]
    if package_mentions and len(import_matches) != 1:
        fail(f"api/remotes client source has a malformed or duplicate Codex import: {path}")

    type_remote_line = f"export type {{}} from '{remote_spec}'"
    type_types_line = type_export_line
    remote_exports = [
        index for index, line in enumerate(lines)
        if line_without_ending(line).strip().rstrip(";") == type_remote_line
    ]
    type_exports = [
        index for index, line in enumerate(lines)
        if line_without_ending(line).strip().rstrip(";") == type_types_line
    ]
    named_type_export_re = re.compile(
        r"^export type \{[A-Za-z0-9_, ]+\} from ['\"]"
        + re.escape(types_spec)
        + r"['\"]$"
    )
    named_type_exports = [
        index for index, line in enumerate(lines)
        if named_type_export_re.fullmatch(line_without_ending(line).strip().rstrip(";"))
    ]
    type_star_exports = [
        index for index, line in enumerate(lines)
        if line_without_ending(line).strip().rstrip(";")
        == f"export type * from '{types_spec}'"
    ]
    legacy_type_exports = [
        index for index, line in enumerate(lines)
        if legacy_types_spec in line and line_without_ending(line).lstrip().startswith('export type')
    ]
    event_exports = [
        index for index, line in enumerate(lines)
        if line_without_ending(line).strip().rstrip(';') == event_export_line
    ]
    if len(remote_exports) > 1 or len(type_exports) > 1 or len(named_type_exports) > 1 or len(type_star_exports) > 1:
        fail(f"api/remotes client source has duplicate Codex type exports: {path}")
    if len(legacy_type_exports) > 1 or len(event_exports) > 1:
        fail(f"api/remotes client source has duplicate Codex safe-face exports: {path}")

    # The contribution list is deliberately checked independently of imports;
    # this catches a hand-edited source that silently drops the mount.
    contribution_lines = [
        index for index, line in enumerate(lines)
        if re.search(r"\bcodexRemote\s*,", line_without_ending(line))
    ]
    if len(contribution_lines) > 1:
        fail(f"api/remotes client source has duplicate Codex Remote mounts: {path}")

    new_lines = list(lines)
    changed = False

    if not import_matches:
        anchor_re = re.compile(
            r"^import[ \t]+pluginInventoryRemote[ \t]+from[ \t]+['\"]"
            r"@deepseek-ai/dsh-host-plugin-inventory/remote['\"];?[ \t]*$"
        )
        anchors = [
            index for index, line in enumerate(new_lines)
            if anchor_re.fullmatch(line_without_ending(line))
        ]
        if len(anchors) != 1:
            fail(f"api/remotes client source is missing the plugin-inventory import anchor: {path}")
        new_lines.insert(anchors[0] + 1, f"import codexRemote from '{remote_spec}'{newline}")
        changed = True

    if not remote_exports:
        anchor_re = re.compile(
            r"^export type \{\}\s+from\s+['\"]"
            r"@deepseek-ai/dsh-host-plugin-inventory/remote['\"];?[ \t]*$"
        )
        anchors = [
            index for index, line in enumerate(new_lines)
            if anchor_re.fullmatch(line_without_ending(line))
        ]
        if len(anchors) != 1:
            fail(f"api/remotes client source is missing the plugin-inventory type anchor: {path}")
        new_lines.insert(anchors[0] + 1, type_remote_line + newline)
        changed = True

    if named_type_exports and not type_exports:
        if type_star_exports or legacy_type_exports:
            fail(f"api/remotes client source has conflicting Codex type exports: {path}")
        new_lines[named_type_exports[0]] = type_types_line + newline
        changed = True
    elif legacy_type_exports and not type_exports:
        if type_star_exports:
            fail(f"api/remotes client source has both legacy and star Codex type exports: {path}")
        new_lines[legacy_type_exports[0]] = type_types_line + newline
        changed = True
    elif not type_exports:
        if type_star_exports:
            star_lines = [
                index for index, line in enumerate(new_lines)
                if line_without_ending(line).strip().rstrip(";")
                == f"export type * from '{types_spec}'"
            ]
            if len(star_lines) != 1:
                fail(f"api/remotes client source has a malformed Codex type export: {path}")
            new_lines[star_lines[0]] = type_types_line + newline
            changed = True
        else:
            anchor_re = re.compile(
                r"^export type \{\}\s+from\s+['\"]"
                r"@deepseek-ai/dsh-host-plugin-inventory/remote['\"];?[ \t]*$"
            )
            anchors = [
                index for index, line in enumerate(new_lines)
                if anchor_re.fullmatch(line_without_ending(line))
            ]
            if len(anchors) != 1:
                fail(f"api/remotes client source is missing the type vocabulary anchor: {path}")
            new_lines.insert(anchors[0] + 1, type_types_line + newline)
            changed = True

    if not event_exports:
        # Keep the event map in the same browser-safe assembly package.  This
        # is a type-only edge and does not mount another Remote namespace.
        type_anchor = [
            index for index, line in enumerate(new_lines)
            if line_without_ending(line).strip().rstrip(';') == type_types_line
        ]
        if len(type_anchor) != 1:
            fail(f"api/remotes client source is missing the Codex safe type anchor: {path}")
        new_lines.insert(type_anchor[0] + 1, event_export_line + newline)
        changed = True

    if not contribution_lines:
        anchors = [
            index for index, line in enumerate(new_lines)
            if re.search(r"\bpluginInventoryRemote\s*,", line_without_ending(line))
        ]
        if len(anchors) != 1:
            fail(f"api/remotes client source is missing the plugin-inventory mount anchor: {path}")
        line = line_without_ending(new_lines[anchors[0]])
        indent = line[: len(line) - len(line.lstrip())]
        new_lines.insert(anchors[0] + 1, indent + "codexRemote," + newline)
        changed = True

    # Re-evaluate the final shape after insertions so a malformed source never
    # receives a manifest hash that appears healthy on the next run.
    result = "".join(new_lines)
    if result.count(f"'{remote_spec}'") != 2:
        fail(f"api/remotes client source has an unexpected Codex Remote reference count: {path}")
    if result.count(f"'{types_spec}'") != 1 or legacy_types_spec in result or "export type * from" in result:
        fail(f"api/remotes client source has an unexpected Codex type reference count: {path}")
    if result.count(f"'{event_types_spec}'") != 1:
        fail(f"api/remotes client source has an unexpected Codex event type reference count: {path}")
    if result.count("codexRemote,") != 1:
        fail(f"api/remotes client source has an unexpected Codex Remote mount count: {path}")
    return result, changed


def rewrite_api_remotes_tsconfig_client(path: Path, dry_run: bool) -> tuple[str, bool]:
    """Keep api/remotes' Client leaf independent of the Host project.

    The generated Remote/type artifacts are consumed through the workspace
    package exports after the Host build.  Referencing the Host project from
    this Client leaf drags its Cordis ``Context.sessions`` augmentation into
    the browser graph and creates the SessionStore/ISessions merge conflict.
    Migrate an older overlay by removing that exact object block; all other
    references remain untouched.
    """

    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        fail(f"cannot read {path}: {exc}")
    lines, newline = split_lines(text)
    target_paths = [
        index for index, line in enumerate(lines)
        if '"path": "../../host/codex"' in line
    ]
    if len(target_paths) > 1:
        fail(f"api/remotes client tsconfig has duplicate Codex Host references: {path}")
    if not target_paths:
        return text, False

    if len(target_paths) != 1:
        fail(f"api/remotes client tsconfig has a malformed Codex Host reference: {path}")
    anchor_path_index = target_paths[0]
    anchor_open_index = anchor_path_index
    while anchor_open_index >= 0 and not re.fullmatch(
        r"^[ \t]*\{[ \t]*$", line_without_ending(lines[anchor_open_index])
    ):
        anchor_open_index -= 1
    if anchor_open_index < 0:
        fail(f"api/remotes client tsconfig has a malformed Codex Host block: {path}")
    anchor_close_index = anchor_path_index + 1
    while anchor_close_index < len(lines) and not re.fullmatch(
        r"^[ \t]*\},?[ \t]*$", line_without_ending(lines[anchor_close_index])
    ):
        anchor_close_index += 1
    if anchor_close_index >= len(lines):
        fail(f"api/remotes client tsconfig has a malformed Codex Host block: {path}")
    new_lines = lines[:anchor_open_index] + lines[anchor_close_index + 1:]
    return "".join(new_lines), True


def rewrite_api_remotes_package(path: Path, dry_run: bool) -> tuple[str, bool]:
    """Add the Host package to api/remotes peer/dev dependency faces."""

    try:
        text = path.read_text(encoding="utf-8")
        package = json.loads(text)
    except OSError as exc:
        fail(f"cannot read {path}: {exc}")
    except json.JSONDecodeError as exc:
        fail(f"api/remotes package.json is not valid JSON: {exc}")

    changed = False
    for section in ("peerDependencies", "devDependencies"):
        values = package.get(section)
        if not isinstance(values, dict):
            fail(f"api/remotes package.json has no {section} object: {path}")
        current = values.get(HOST_PACKAGE)
        if current is not None and current != "workspace:^":
            fail(
                f"api/remotes package.json has a drifted {HOST_PACKAGE} {section}: "
                f"{current!r}"
            )
        if current is None:
            # Keep insertion adjacent to the existing Host package where the
            # upstream manifest already groups generated Remote providers.
            next_values: dict[str, str] = {}
            inserted = False
            for key, value in values.items():
                next_values[key] = value
                if key == HOST_DEPENDENCY_ANCHOR:
                    next_values[HOST_PACKAGE] = "workspace:^"
                    inserted = True
            if not inserted:
                fail(
                    f"api/remotes package.json is missing the {HOST_DEPENDENCY_ANCHOR} "
                    f"anchor in {section}: {path}"
                )
            package[section] = next_values
            changed = True

    if not changed:
        return text, False
    result = json.dumps(package, indent=2) + "\n"
    try:
        parsed = json.loads(result)
    except json.JSONDecodeError as exc:
        fail(f"refusing to write invalid api/remotes package.json: {exc}")
    for section in ("peerDependencies", "devDependencies"):
        values = parsed.get(section)
        if not isinstance(values, dict) or values.get(HOST_PACKAGE) != "workspace:^":
            fail(f"refusing to write {HOST_PACKAGE} outside api/remotes {section}")
    return result, True


def rewrite_cordis_patch(path: Path, dry_run: bool) -> tuple[str, bool]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        fail(f"cannot read {path}: {exc}")
    lines, newline = split_lines(text)

    voice_id_re = re.compile(r"^[ \t]*-[ \t]*id:[ \t]*ui-voice[ \t]*$")
    voice_name_re = re.compile(
        r"^[ \t]*name:[ \t]*'@deepseek-ai/dsh-client-ui-voice'[ \t]*$"
    )
    voice_matches = [
        index
        for index, line in enumerate(lines)
        if voice_id_re.fullmatch(line_without_ending(line))
    ]
    if "id: ui-voice" in text and not voice_matches:
        fail(f"cordis.patch.yml has a malformed ui-voice id anchor: {path}")
    if len(voice_matches) > 1:
        fail(f"cordis.patch.yml has duplicate ui-voice entries: {path}")
    if voice_matches:
        index = voice_matches[0]
        if index + 1 >= len(lines) or not voice_name_re.fullmatch(
            line_without_ending(lines[index + 1])
        ):
            fail(f"cordis.patch.yml ui-voice entry has an unexpected name: {path}")

    codex_id_re = re.compile(r"^[ \t]*-[ \t]*id:[ \t]*codex[ \t]*$")
    codex_name_re = re.compile(
        r"^[ \t]*name:[ \t]*'@deepseek-ai/dsh-host-codex'[ \t]*$"
    )
    codex_matches = [
        index for index, line in enumerate(lines)
        if codex_id_re.fullmatch(line_without_ending(line))
    ]
    if "id: codex" in text and not codex_matches:
        fail(f"cordis.patch.yml has a malformed Codex Host id anchor: {path}")
    if len(codex_matches) > 1:
        fail(f"cordis.patch.yml has duplicate Codex Host entries: {path}")
    if codex_matches:
        index = codex_matches[0]
        if index + 1 >= len(lines) or not codex_name_re.fullmatch(
            line_without_ending(lines[index + 1])
        ):
            fail(f"cordis.patch.yml Codex Host entry has an unexpected name: {path}")

    anchor_id_re = re.compile(r"^(?P<indent>[ \t]*)-[ \t]*id:[ \t]*ui-trajectory[ \t]*$")
    anchor_name_re = re.compile(
        r"^[ \t]*name:[ \t]*'@deepseek-ai/dsh-client-ui-trajectory'[ \t]*$"
    )
    anchors = [
        index
        for index, line in enumerate(lines)
        if anchor_id_re.fullmatch(line_without_ending(line))
    ]
    if len(anchors) != 1:
        fail(
            "cordis.patch.yml must contain exactly one ui-trajectory id anchor; "
            f"found {len(anchors)}: {path}"
        )
    anchor_index = anchors[0]
    if anchor_index + 1 >= len(lines) or not anchor_name_re.fullmatch(
        line_without_ending(lines[anchor_index + 1])
    ):
        fail(f"cordis.patch.yml ui-trajectory anchor has drifted: {path}")
    changed = False
    new_lines = list(lines)
    if not voice_matches:
        indent = anchor_id_re.fullmatch(
            line_without_ending(new_lines[anchor_index])
        ).group("indent")
        inserted = [
            indent + "- id: ui-voice" + newline,
            indent + "  name: '@deepseek-ai/dsh-client-ui-voice'" + newline,
        ]
        new_lines[anchor_index + 2 : anchor_index + 2] = inserted
        changed = True

    if not codex_matches:
        host_anchor_re = re.compile(
            r"^(?P<indent>[ \t]*)-[ \t]*id:[ \t]*plugin-inventory[ \t]*$"
        )
        host_anchors = [
            index for index, line in enumerate(new_lines)
            if host_anchor_re.fullmatch(line_without_ending(line))
        ]
        if len(host_anchors) != 1:
            fail(
                "cordis.patch.yml must contain exactly one plugin-inventory host anchor; "
                f"found {len(host_anchors)}: {path}"
            )
        host_index = host_anchors[0]
        if host_index + 1 >= len(new_lines) or not re.fullmatch(
            r"^[ \t]*name:[ \t]*'@deepseek-ai/dsh-host-plugin-inventory'[ \t]*$",
            line_without_ending(new_lines[host_index + 1]),
        ):
            fail(f"cordis.patch.yml plugin-inventory host anchor has drifted: {path}")
        indent = host_anchor_re.fullmatch(
            line_without_ending(new_lines[host_index])
        ).group("indent")
        inserted = [
            indent + "- id: codex" + newline,
            indent + "  name: '@deepseek-ai/dsh-host-codex'" + newline,
        ]
        new_lines[host_index + 2 : host_index + 2] = inserted
        changed = True

    return "".join(new_lines), changed


def rewrite_package_json(path: Path, dry_run: bool) -> tuple[str, bool]:
    try:
        text = path.read_text(encoding="utf-8")
        package = json.loads(text)
    except OSError as exc:
        fail(f"cannot read {path}: {exc}")
    except json.JSONDecodeError as exc:
        fail(f"web-app package.json is not valid JSON: {exc}")

    dependencies = package.get("dependencies")
    if not isinstance(dependencies, dict):
        fail(f"web-app package.json has no dependencies object: {path}")
    if dependencies.get(PLUGIN_DEPENDENCY_ANCHOR) != "workspace:^":
        fail(
            "web-app package.json is missing the expected dependency anchor: "
            f"{PLUGIN_DEPENDENCY_ANCHOR}"
        )

    required = (PLUGIN_PACKAGE, HOST_PACKAGE)
    for package_name in required:
        current = dependencies.get(package_name)
        if current is not None and current != "workspace:^":
            fail(
                f"web-app package.json has a drifted {package_name} dependency: "
                f"{current!r} (expected 'workspace:^')"
            )

    lines, newline = split_lines(text)
    changed = False

    def add_dependency(package_name: str, anchor_name: str) -> None:
        nonlocal lines, changed
        key_re = re.compile(
            r"^[ \t]*\"" + re.escape(package_name) + r"\"[ \t]*:"
        )
        key_matches = [
            index for index, line in enumerate(lines)
            if key_re.match(line_without_ending(line))
        ]
        if len(key_matches) > 1:
            fail(f"web-app package.json has duplicate {package_name} dependency keys: {path}")
        if dependencies.get(package_name) == "workspace:^":
            if len(key_matches) != 1:
                fail(f"web-app package.json dependency is not at a precise key anchor: {path}")
            return
        if key_matches:
            fail(f"web-app package.json has a malformed {package_name} dependency key: {path}")

        anchor_re = re.compile(
            r"^(?P<indent>[ \t]*)\"" + re.escape(anchor_name)
            + r"\"[ \t]*:[ \t]*\"workspace:\^\"(?P<comma>,?)[ \t]*$"
        )
        anchors = [
            index for index, line in enumerate(lines)
            if anchor_re.fullmatch(line_without_ending(line))
        ]
        if len(anchors) != 1:
            fail(
                "web-app package.json must contain exactly one comma-terminated "
                f"{anchor_name} anchor; found {len(anchors)}: {path}"
            )
        anchor_index = anchors[0]
        anchor_match = anchor_re.fullmatch(line_without_ending(lines[anchor_index]))
        assert anchor_match is not None
        following = next(
            (
                line_without_ending(line).strip()
                for line in lines[anchor_index + 1 :]
                if line_without_ending(line).strip()
            ),
            "",
        )
        if not anchor_match.group("comma"):
            if not following.startswith("}"):
                fail(f"web-app package.json dependency anchor has unexpected drift: {path}")
            lines[anchor_index] = line_without_ending(lines[anchor_index]) + "," + newline
            following = "}"
        comma = "" if following.startswith("}") else ","
        indent = anchor_match.group("indent")
        inserted = indent + f'"{package_name}": "workspace:^"{comma}' + newline
        lines = lines[: anchor_index + 1] + [inserted] + lines[anchor_index + 1 :]
        dependencies[package_name] = "workspace:^"
        changed = True

    add_dependency(PLUGIN_PACKAGE, PLUGIN_DEPENDENCY_ANCHOR)
    add_dependency(HOST_PACKAGE, HOST_DEPENDENCY_ANCHOR)
    result = "".join(lines)
    try:
        parsed_result = json.loads(result)
    except json.JSONDecodeError as exc:
        fail(f"refusing to write invalid web-app package.json: {exc}")
    result_dependencies = parsed_result.get("dependencies")
    if (
        not isinstance(result_dependencies, dict)
        or any(result_dependencies.get(name) != "workspace:^" for name in required)
    ):
        fail("refusing to write required web-app dependencies outside dependencies")
    return result, changed


def atomic_write(path: Path, content: str) -> None:
    """Atomically replace one text file, retaining its mode when present."""

    fd, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.codex-", dir=str(path.parent))
    temporary = Path(temporary_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o644
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    except Exception:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass
        raise


def atomic_copy(source: Path, destination: Path) -> None:
    """Copy one managed source file and atomically replace its destination."""

    fd, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.name}.codex-", dir=str(destination.parent)
    )
    temporary = Path(temporary_name)
    os.close(fd)
    try:
        shutil.copy2(source, temporary, follow_symlinks=False)
        with temporary.open("rb") as handle:
            os.fsync(handle.fileno())
        os.replace(temporary, destination)
    except Exception:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass
        raise


def build_manifest(
    source_hashes: dict[str, str],
    host_source_hashes: dict[str, str],
    registration_hashes: dict[str, str],
    previous: dict[str, object] | None,
    lock: dict[str, str] | None,
    catalog: dict[str, str] | None,
) -> dict[str, object]:
    if lock is None and previous is not None:
        previous_lock = previous.get("lock")
        if isinstance(previous_lock, dict):
            lock = {
                key: value for key, value in previous_lock.items() if isinstance(value, str)
            }
    if catalog is None and previous is not None:
        previous_catalog = previous.get("catalog")
        if isinstance(previous_catalog, dict):
            previous_files = previous_catalog.get("files")
            if (
                previous_catalog.get("generator") == "gen-persistence-catalog"
                and isinstance(previous_files, dict)
            ):
                catalog = {
                    key: value
                    for key, value in previous_files.items()
                    if isinstance(key, str) and isinstance(value, str)
                }

    result: dict[str, object] = {
        "schemaVersion": MANIFEST_SCHEMA,
        "installer": "dsh-plugin",
        "source": "dsh-plugin",
        "target": PLUGIN_TARGET.as_posix(),
        "sourceTreeSha256": tree_digest(source_hashes),
        "files": dict(sorted(source_hashes.items())),
        "hostSourceTreeSha256": tree_digest(host_source_hashes),
        "hostFiles": dict(sorted(host_source_hashes.items())),
        "registrations": dict(sorted(registration_hashes.items())),
        "lock": lock,
    }
    if catalog is not None:
        result["catalog"] = {
            "generator": "gen-persistence-catalog",
            "files": dict(sorted(catalog.items())),
        }
    return result


def manifest_json(manifest: dict[str, object]) -> str:
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    harness_value = args.harness or (
        Path(os.environ["DSH_HARNESS"]) if os.environ.get("DSH_HARNESS") else None
    )
    if harness_value is None:
        fail("pass --harness PATH or set DSH_HARNESS")
    harness_input = harness_value.expanduser()
    source_input = args.source.expanduser()
    host_source_input = args.host_source.expanduser()
    ensure_no_symlink(harness_input, "harness checkout")
    ensure_no_symlink(source_input, "plugin source")
    ensure_no_symlink(host_source_input, "Codex Host source")
    harness = harness_input.resolve()
    source = source_input.resolve()
    host_source = host_source_input.resolve()

    if harness == Path(harness.anchor):
        fail("refusing to operate on filesystem root as harness")
    if not harness.is_dir():
        fail(f"harness checkout does not exist or is not a directory: {harness}")
    ensure_no_symlink(harness, "harness checkout")
    if not (harness / "package.json").is_file():
        fail(f"harness checkout has no package.json: {harness}")
    if not source.is_dir():
        fail(f"plugin source does not exist or is not a directory: {source}")
    if not host_source.is_dir():
        fail(f"Codex Host source does not exist or is not a directory: {host_source}")
    ensure_no_symlink(source, "plugin source")
    ensure_no_symlink(host_source, "Codex Host source")
    if args.record_lock:
        lock_path = harness / "pnpm-lock.yaml"
        if not lock_path.is_file() or lock_path.is_symlink():
            fail(f"cannot record missing or symlinked pnpm lockfile: {lock_path}")
    if args.record_catalog and args.dry_run:
        fail("--record-catalog cannot be combined with --dry-run")

    files = validate_source(source, PLUGIN_PACKAGE, "plugin")
    host_files = validate_source(host_source, HOST_PACKAGE, "Codex Host")
    target = harness / PLUGIN_TARGET
    host_target = harness / HOST_TARGET
    for parent in target.parents:
        if parent == harness:
            break
        ensure_no_symlink(parent, "plugin target parent")
    for parent in host_target.parents:
        if parent == harness:
            break
        ensure_no_symlink(parent, "Codex Host target parent")
    manifest = load_manifest(target)
    validate_manifest_registrations(harness, manifest)
    transformed_plugin_files = {
        Path("tsconfig.json"): assembled_client_tsconfig(
            source / "tsconfig.json"
        ),
        Path("tsconfig.client.json"): assembled_client_tsconfig(
            source / "tsconfig.client.json"
        ),
    }
    transformed_host_files = {
        Path("tsconfig.json"): assembled_host_tsconfig(host_source / "tsconfig.json")
    }
    transformed_host_files.update({
        relative: transformed
        for relative in host_files
        if (transformed := assembled_host_test_source(host_source, relative)) is not None
    })
    planned_files, obsolete, source_hashes = validate_plugin_tree(
        source,
        target,
        files,
        manifest,
        transformed_files=transformed_plugin_files,
    )
    planned_host_files, obsolete_host_files, host_source_hashes = validate_plugin_tree(
        host_source,
        host_target,
        host_files,
        manifest,
        manifest_key="hostFiles",
        label="Codex Host",
        transformed_files=transformed_host_files,
    )

    tsconfig = harness / REGISTRATION_RELATIVES[0]
    host_tsconfig = harness / REGISTRATION_RELATIVES[1]
    api_remotes_client = harness / REGISTRATION_RELATIVES[2]
    api_remotes_package = harness / REGISTRATION_RELATIVES[3]
    api_remotes_tsconfig = harness / REGISTRATION_RELATIVES[4]
    cordis_patch = harness / REGISTRATION_RELATIVES[5]
    web_package = harness / REGISTRATION_RELATIVES[6]
    api_proxy = harness / REGISTRATION_RELATIVES[7]
    client_manager = harness / REGISTRATION_RELATIVES[8]
    for registration in (
        tsconfig,
        host_tsconfig,
        api_remotes_client,
        api_remotes_package,
        api_remotes_tsconfig,
        cordis_patch,
        web_package,
        api_proxy,
        client_manager,
    ):
        for parent in registration.parents:
            if parent == harness:
                break
            ensure_no_symlink(parent, "DSH registration parent")
        ensure_no_symlink(registration, "DSH registration file")
        if not registration.is_file():
            fail(f"pinned DSH registration file is missing: {registration}")

    tsconfig_result, tsconfig_changed = rewrite_tsconfig(tsconfig, args.dry_run)
    host_tsconfig_result, host_tsconfig_changed = rewrite_host_tsconfig(
        host_tsconfig, args.dry_run
    )
    api_remotes_client_result, api_remotes_client_changed = rewrite_api_remotes_client(
        api_remotes_client, args.dry_run
    )
    api_remotes_package_result, api_remotes_package_changed = rewrite_api_remotes_package(
        api_remotes_package, args.dry_run
    )
    api_remotes_tsconfig_result, api_remotes_tsconfig_changed = (
        rewrite_api_remotes_tsconfig_client(api_remotes_tsconfig, args.dry_run)
    )
    cordis_result, cordis_changed = rewrite_cordis_patch(cordis_patch, args.dry_run)
    package_result, package_changed = rewrite_package_json(web_package, args.dry_run)
    api_proxy_result, api_proxy_changed = rewrite_api_proxy_codex_session_semantics(
        api_proxy, args.dry_run
    )
    client_manager_result, client_manager_changed = rewrite_client_manager_session_metadata(
        client_manager, args.dry_run
    )

    # Preflight generated artifacts before writing the plugin or registration
    # anchors so a missing/symlinked catalog cannot leave a half-installed
    # manifest behind.
    catalog = persistence_catalog_hashes(harness) if args.record_catalog else None

    changes = [
        *(f"copy {relative}" for relative in planned_files),
        *(f"remove obsolete managed file {relative}" for relative in obsolete),
        *(f"copy Codex Host {relative}" for relative in planned_host_files),
        *(f"remove obsolete managed Codex Host file {relative}" for relative in obsolete_host_files),
        *("register tsconfig.client.json" for _ in [tsconfig_changed] if tsconfig_changed),
        *("register tsconfig.host.json" for _ in [host_tsconfig_changed] if host_tsconfig_changed),
        *("register api/remotes client assembly" for _ in [api_remotes_client_changed] if api_remotes_client_changed),
        *("register api/remotes package.json" for _ in [api_remotes_package_changed] if api_remotes_package_changed),
        *("register api/remotes client tsconfig" for _ in [api_remotes_tsconfig_changed] if api_remotes_tsconfig_changed),
        *("register cordis.patch.yml" for _ in [cordis_changed] if cordis_changed),
        *("register web-app/package.json" for _ in [package_changed] if package_changed),
        *("register Codex Session-list semantics" for _ in [api_proxy_changed] if api_proxy_changed),
        *("register live Session-list metadata mirror" for _ in [client_manager_changed] if client_manager_changed),
    ]
    if manifest is None and args.dry_run:
        changes.append("write managed manifest")
    if args.dry_run:
        if args.record_lock:
            fail("--record-lock cannot be combined with --dry-run")
        print(f"[dsh-plugin] dry-run: {len(changes)} change(s) for {harness}")
        for change in changes:
            print(f"[dsh-plugin] would {change}")
        if not changes:
            print("[dsh-plugin] already synchronized")
        return 0

    if target.exists():
        ensure_no_symlink(target, "plugin target")
    target.mkdir(parents=True, exist_ok=True)
    ensure_no_symlink(target, "plugin target")
    for relative in planned_files:
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        for parent in destination.parents:
            if parent == target:
                break
            ensure_no_symlink(parent, "plugin target parent")
        transformed = transformed_plugin_files.get(relative)
        if transformed is None:
            atomic_copy(source / relative, destination)
        else:
            atomic_write(destination, transformed.decode("utf-8"))
    for relative in obsolete:
        destination = target / relative
        if destination.exists() or destination.is_symlink():
            if destination.is_symlink() or not destination.is_file():
                fail(f"managed obsolete path changed before removal: {relative}")
            destination.unlink()

    if host_target.exists():
        ensure_no_symlink(host_target, "Codex Host target")
    host_target.mkdir(parents=True, exist_ok=True)
    ensure_no_symlink(host_target, "Codex Host target")
    for relative in planned_host_files:
        destination = host_target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        for parent in destination.parents:
            if parent == host_target:
                break
            ensure_no_symlink(parent, "Codex Host target parent")
        transformed = transformed_host_files.get(relative)
        if transformed is None:
            atomic_copy(host_source / relative, destination)
        else:
            atomic_write(destination, transformed.decode("utf-8"))
    for relative in obsolete_host_files:
        destination = host_target / relative
        if destination.exists() or destination.is_symlink():
            if destination.is_symlink() or not destination.is_file():
                fail(f"managed obsolete Codex Host path changed before removal: {relative}")
            destination.unlink()

    if tsconfig_changed:
        atomic_write(tsconfig, tsconfig_result)
    if host_tsconfig_changed:
        atomic_write(host_tsconfig, host_tsconfig_result)
    if api_remotes_client_changed:
        atomic_write(api_remotes_client, api_remotes_client_result)
    if api_remotes_package_changed:
        atomic_write(api_remotes_package, api_remotes_package_result)
    if api_remotes_tsconfig_changed:
        atomic_write(api_remotes_tsconfig, api_remotes_tsconfig_result)
    if cordis_changed:
        atomic_write(cordis_patch, cordis_result)
    if package_changed:
        atomic_write(web_package, package_result)
    if api_proxy_changed:
        atomic_write(api_proxy, api_proxy_result)
    if client_manager_changed:
        atomic_write(client_manager, client_manager_result)

    lock: dict[str, str] | None = None
    if args.record_lock:
        lock_path = harness / "pnpm-lock.yaml"
        lock = {"path": "pnpm-lock.yaml", "sha256": sha256_file(lock_path)}
        if args.pnpm_version:
            lock["pnpmVersion"] = args.pnpm_version

    registration_hashes = {
        relative.as_posix(): sha256_file(harness / relative)
        for relative in REGISTRATION_RELATIVES
    }
    next_manifest = build_manifest(
        source_hashes,
        host_source_hashes,
        registration_hashes,
        manifest,
        lock,
        catalog,
    )
    manifest_path = target / MANIFEST_RELATIVE
    old_manifest_text = manifest_json(manifest) if manifest is not None else None
    next_manifest_text = manifest_json(next_manifest)
    if old_manifest_text != next_manifest_text or not manifest_path.exists():
        managed_dir = target / MANAGED_DIR
        if managed_dir.exists() and managed_dir.is_symlink():
            fail(f"managed directory must not be a symlink: {managed_dir}")
        managed_dir.mkdir(parents=True, exist_ok=True)
        atomic_write(manifest_path, next_manifest_text)
        changes.append("write managed manifest")

    if changes:
        print(f"[dsh-plugin] synchronized {len(changes)} change(s) into {target}")
    else:
        print(f"[dsh-plugin] already synchronized: {target}")
    print(
        "[dsh-plugin] source overlay only; generated lib is not managed. "
        "Run scripts/bootstrap-dsh.sh (recommended), or rebuild the pinned "
        "harness before restarting dsh web."
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except InstallerError as exc:
        print(f"[dsh-plugin] ERROR: {exc}", file=sys.stderr)
        raise SystemExit(2)
